# **Regresion**

La regresion es un tipo de técnica estadística utilizada para modelar la relacion entre variables y predecir valores numéricos continuos. Es decir, la regresión se utiliza cuando queremos predecir un resultado numérico basado en la relación entre un conjunto de variables independientes (características o atributos) y un variable dependiente o de respuesta. En la regresión, el objetivo es encontrar una función que pueda mapear las variables independientes a la variable dependiente de manera óptima, de modo que cuando se le proporcionen nuevo valores de características, pueda predecir el velor correspondiente de la variable objetivo.

Dentro de las principales técnicas de regresión se tiene:

1. Regresión Lineal Simple
2. Regresión Lineal Multiple
3. Regresión Polinomial
4. Regresión de Vecino más Cercano (K-NN)
5. Regresión de Maquina de Soporte Vectorial
6. Árboles de Regresión
7. Bosques Aleatorios (Random Forest)
8. Regresión mediante Redes Neuronales
9. Regresión Ridge (L2)
10. Regresión LASSO (L1)
11. Regresión Elastic Net

Entre otros

## **Importación de librerias**

In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report

# Librerias para metricas
from sklearn import metrics

# Regresion lineal
from sklearn.linear_model import LinearRegression

# Regresion logistica
from sklearn.linear_model import LogisticRegression

# Arbol de decision
from sklearn.tree import DecisionTreeRegressor

# Red neuronal perceptron multicapa
from sklearn.neural_network import MLPRegressor

# Knn para regresion
from sklearn.neighbors import KNeighborsRegressor

# Maquina de vector de soporte
from sklearn.svm import SVR

## **Descripción del dataset**

El problema que veremos es el conjunto de datos del precio de la vivienda en Londres. El conjunto de datos describe propiedades de casas en los suburbios de Londres y se desea modelar el precio de casas en estos barrios en miles de euros. Con tal, esto es un modelo predictivo de regresión. Hay variables de entrada que describen las propiedades de un determinado barrio de Londres. La lista completa de atributos en este conjunto de datos es la siguiente:

**1. CRIM:** tasa de ciminalidad.</br>
**2. ZN:** Proporción de terreno residencial dividido en zonas para lotes de más de 25,000 pies cuadrados.</br>
**3. INDUS:** Proporción de negocios no minoristas.</br>
**4. CHAS:** Variable ficticia del rio (=1 si el tramo limita con el rio; 0 en caso contrario).</br>
**5. NOX:** concentración de óxido nitricos (10ppm).</br>
**6. RM:** número medio de habitaciones por vivienda</br>
**7. EDAD:** proporción de viviendas ocupadas por sus propietarios contruidas antes de 1940</br>
**8. DIS:** distancia ponderadas a los centro de empleo en Londres.</br>
**9. RAD:** indice de accesibilidad a carretera radiales.</br>
**10. IMPUESTO:** tasa del impuesto sobre el valor total de propiedad por cada 10,000 euros</br>
**11. PTRATIO:** número de alumnos por docente y ciudad.</br>
**12. B:** 1000(B 0:63) 2 donde B es la proporción de inmigrantes.</br>
**13. LSTAT:** % de menor estatus de poblacion.</br>

**Variable objetivo**

**14. MEDV:** Valor medio de las viviendas ocupadas por sus propietarios en miles de euros.

## **Importación de datos**

In [18]:
dataset = pd.read_csv('./regresion_vivienda_londres.csv', sep=',', header=0)
dataset.head()

CRIMINALIDAD    ZN  INDUS  CHAS    NOX     RM  EDAD     DIS  RAD  IMPUESTO  \
0       0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1       296   
1       0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2       242   
2       0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2       242   
3       0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3       222   
4       0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3       222   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

## **Separación de datos para entrenamiento y test**

In [19]:
X = dataset.drop(['MEDV'], axis=1)
y = dataset['MEDV']

# Separacion de datos en entrenamiento y test
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=5, test_size=0.3)

## **1. Modelo de regresión lineal multiple**

El modelo de Regresión Lineal Múltiple es una extesión del modelo de Regresion Lineal. La ecuación general del Modelo de Regresión Lineal Múltiple se representa como: $y = a_1x_1 + a_2x_2 + ... +a_nx_n + b$

In [4]:
# Creación de modelo
modelo = LinearRegression()

# Training
modelo.fit(X_train, y_train)

LinearRegression()

## **Métrica R2**

El coeficiente de determinación, comúnmente conocido como R2 (pronunciado como R cuadrado), es una métrica utilizada en la regresión para evaluar el rendimiento de un modelo de regresión. R2 es una medida estadística que indica qué proporción de la variabilidad de la variable dependiente puede ser explicada por las variables independientes incluidas en el modelo.

In [5]:
# Determinar R^2
# R^2 = 1 - (sumatoria (yi - pi)^2 / sumatoria(yi - yprom)^2)
# donde:
#       yi : son los valores que toma la variable objetivo
#       pi : son los valores de la predicción
#       yprom : es el valor medio de los valores que toma la variable objetivo

# oscila: -infinito < --- > 1
# Un valor de R2 menor a 0 => Muy baja de capacidad explicativa de la recta
# Un valor de R2 cercano a 0 => Baja capacidad explicativa de la recta
# Un valor de R2 proximo a 1 => Alta capacidad explicativa de la recta

y_pred = modelo.predict(X_test)
metrics.r2_score(y_test, y_pred)

0.7299069327752883

## **Coeficientes de regresión lineal**

In [6]:
# Coeficientes de la ecuacion de regresion
modelo.intercept_, modelo.coef_

(32.15628821793741,
 array([-1.04505039e-01,  4.14897707e-02, -1.61319423e-02,  3.12340405e+00,
        -1.69767450e+01,  4.18366013e+00, -6.40329010e-03, -1.33956132e+00,
         2.88839559e-01, -1.12708522e-02, -9.21252552e-01,  9.64608849e-03,
        -4.49315645e-01]))

## **Nueva Predicción**

In [9]:
nuevo = [[0.0976, 11.5, 7.27, 0, 0.51, 5.2, 38, 5.23, 5, 309, 12.2, 370.5, 15.7]]
pred = modelo.predict(nuevo)
pred

c:\Users\HARVEY\anaconda3\envs\machine-learning\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([21.59544712])

## **2. Modelo de regresión con árbol de decisión**

La regresión con árbol de decisión es una técnia de aprendizaje automático utilizada para realizar predicciones de lvalorres numpericos continuos. A diferencia de la regresión lineal, que utiliza una función lineal para modelar la relación entre variables, los árboles de decisión deividen el espaicon de características en regiones más pequeñas y contruyen un árbol para tomar decisiones basadas en reglas lógicas.

El árbol de decisión se contruye dividiendo recursivamente el conjunto de datos en subconjuntos más pequeños y homogéneos, donde cada división se realiza en función de una característica específica y un umbral. Cada hoja de árbol representa una región del espacio o característica y tiene asociado un valor numérico que representa la predicción para los datos que caen en esa región.

Durante la construcción del árbol, se busca la división que minimice el error de predicción en cada subconjunto. El algoritmo del árbol de decisión utiliza diversas métricas para evaluar la calidad de una divis<arianza.

Una vez que el árbol de decisión está construido, se puede utliziar para realizar predicciones de nuevos datos al seguir las reglas definidas en cada nodo interno del árbol, desde la raiz hasta una hoja correspondiente a la region donde caen los datos.


In [10]:
# Entrenamiento del modelo
modelo = DecisionTreeRegressor(max_depth=15)
modelo.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=15)

In [13]:
# Test y score del modelo
y_pred = modelo.predict(X_test)
print(metrics.r2_score(y_test, y_pred))

0.822115197753332


## **Nueva predicción**

In [14]:
# predicción del modelo
nuevo = [[0.0976, 11.5, 7.27, 0, 0.51, 5.2, 38, 5.23, 5, 309, 12.2, 370.5, 15.7]]
pred = modelo.predict(nuevo)
pred

c:\Users\HARVEY\anaconda3\envs\machine-learning\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([17.6])

## **3. Modelo de regresión con Multi Layer Perceptrón (MLP)**

La regresión con Multi Layer Perceptrón (MLP) es una técnica de aprendizaje automático que utiliza redes neuronales para realizar predicciones de valores numéricos continuos, a diferencia de los modelos de regresión lineal a los árboles de decisión, que tilizan ecuaciones o reglas lógicas para realizar predicciones, los MLP son modelos más complejos y flexibles qeu pueden aprender relaciones no lineales en los datos.

Un MLP consta de múltiples capas de neuronas interconectadas. La primera capa, conocida como la capa de entrada, recibe las características del conjunto de datos. Las capas intemedias, llamadas capas oculatas, relaizan transformaciones no lineales de las entradas para extraer características más complejas y abstractas. La última capa, conocida como capa de salida, proporciona la predicción final del modelo.

In [15]:
# configuracion y entrenamiento de la red neuronal
modelo = MLPRegressor(hidden_layer_sizes=(100, 60, 30, 10))
modelo.fit(X_train, y_train)

c:\Users\HARVEY\anaconda3\envs\machine-learning\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPRegressor(hidden_layer_sizes=(100, 60, 30, 10))

In [17]:
# test y score del modelo
y_pred = modelo.predict(X_test)
print(metrics.r2_score(y_test, y_pred))

0.7324177048795552


## **Nueva predicción**

In [18]:
# Prediccion del modelo
nuevo = [[0.0976, 11.5, 7.27, 0, 0.51, 5.2, 38, 5.23, 5, 309, 12.2, 370.5, 15.7]]
pred = modelo.predict(nuevo)
pred

c:\Users\HARVEY\anaconda3\envs\machine-learning\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MLPRegressor was fitted with feature names
  warnings.warn(


array([19.35256156])

## **4. Modelo de regresión con red neuronal densa - Keras**

Esta arquitectura está compuesta por multiples capas ocultas entre la capa de entrada y la capa de salida, lo que permite aprender relaciones no linelales y representaciones complejas de los datos.

In [12]:
# Regresión con redes neuronales profundas
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
# from keras.wrappers.scikit_learn import KerasRegressor
from scikeras.wrappers import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

In [13]:
def modelo():
    # Creacmos el modelo
    model = Sequential()
    model.add(Dense(13, input_dim=13, kernel_initializer='normal', activation='relu'))
    model.add(Dense(1, kernel_initializer='normal'))
    # Compilamos el modelo
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model

In [14]:
dataframe = read_csv('./regresion_vivienda_londres.csv', sep=',', header=0)
ds = dataframe.values

In [15]:
# Entrenar utilizando validación cruzada k=10
estimador = KerasRegressor(build_fn=modelo, epochs=10, batch_size=5, verbose=0)
kfold = KFold(n_splits=10)

# Separacion de variales predictoras y variables objetivo
X = ds[:,0:13]
Y = ds[:,13]

resultado = cross_val_score(estimator=estimador, X=X, y=Y, cv=kfold)
print("MSE: %.2f +/- (%.2f)" % (resultado.mean(), resultado.std()))

c:\Users\HARVEY\anaconda3\envs\machine-learning\lib\site-packages\scikeras\wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
c:\Users\HARVEY\anaconda3\envs\machine-learning\lib\site-packages\scikeras\wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
c:\Users\HARVEY\anaconda3\envs\machine-learning\lib\site-packages\scikeras\wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
c:\Users\HARVEY\anaconda3\envs\machine-learning\lib\site-packages\scikeras\wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will 

MSE: -0.42 +/- (0.48)


## **Nueva prediccion**

In [16]:
# Predicción del modelo
nuevo = [[0.0976, 11.5, 7.27, 0, 0.51, 5.2, 38, 5.23, 5, 309, 12.2, 370.5, 15.7]]
pred = modelo().predict(nuevo)
pred

1/1 [==============================] - 0s 89ms/step


array([[-0.9788805]], dtype=float32)

## **5. Modelo de regresión con K vecinos más cercanos**

La regresión con el algoritmo de Vecinos más cercanos (KNN, por sus siglas en inglés "K-Nearst Neighbors") es una técnica de aprendizaje automático utilizada para predecir valores numéricos continuos. Aunque K-NN es más conocido par su uso en problemas de clasificación también puede aplicarse a tareas de regresión. A nivel de algoritmo, la principal diferencia entre K-NN para clasificación y K-NN para regresión está en cómo se realiza la predicción y cómo se calcula en valor resultante.

***K-NN para Clasificación***

1. **Predicción**: En el caso de K-NN para clasificación, la predicción se realiza asignando una etiqueta a la clase al punto de interés basándose en la mayoría de las clases entre sus K vecinos más cercanos. El punto de interés se clasifica en la clase que es más frencuente en los K vecinos.

2. **Cálculo de la prediccioón** Para calcular la predicción, se utiliza la moda (la clase más común entre los K vecinos más cercanos al punto de interés)

***K-NN para Regresión***


1. **Predicción** En K-NN para regresión, la predicción se realiza calculando un valor numérico para el punto de interés basándose en los valores de la variable objetivo de sus K vecinos más cercanos. El punto de interés se predice como un valor numérico continuo.

2. **Cálculo de la predicción** Para calcular la predicción, se toma el promedio (o la mediana) de los valores de la variable objetivo de los k vecinos más cercanos al punto de interés. Esta media (o mediana) se toma como el valor de predicción para el punto de interés.

In [20]:
# Entrenamiento del modelo
modelo = KNeighborsRegressor(n_neighbors=6)
modelo.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=6)

In [21]:
# test y score del modelo
y_pred = modelo.predict(X_test)
print(metrics.r2_score(y_test, y_pred))

0.5780440545185784


## **Nueva predicción**

In [22]:
# Predicción del modelo
nuevo = [[0.0976, 11.5, 7.27, 0, 0.51, 5.2, 38, 5.23, 5, 309, 12.2, 370.5, 15.7]]
pred = modelo.predict(nuevo)
pred

c:\Users\HARVEY\anaconda3\envs\machine-learning\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([23.28333333])

## **Modelo de regresión con máquina de vector de soporte**

La regresión con Máquina de Soporte Vectorial (SVM, por sus siglas en inglés "Support Vector Machine") es una técnica de aprendizaje automático que se utiliza tanto para la clasificacion como para regresión. En el contexto de la regresión, se denomina SVM de Regresión (SVR)

En SVR, se busca encontrar una función f(x) que cumpla con las siguientes condiciones:

1. Los puntos de datos de entrenamiento deben estar dentro de una banda (epsilon) alrededor de la función f(x). Esta banda se llama margen y se define por el parámetro epsilón.

2. Se busca minimizar la cantidad de putno de datos que violan el margen. Estos puntos reciben el nombre de vectores de soporte y son los que más influyen en la definición de la función f(x).

3. El objetivo final es encontrar una función f(x) que minimize el error de predicción y cumpla con las condiciones anteriores.

In [23]:
# Entrenamiento del modelo
modelo = SVR(kernel='sigmoid', C=1)
modelo.fit(X_train, y_train)

SVR(C=1, kernel='sigmoid')

In [24]:
# Test y score del modelo
y_pred = modelo.predict(X_test)
print(metrics.r2_score(y_test, y_pred))

0.0370525085007668


## **Nueva predicción**

In [26]:
# Predicción del modelo
nuevo = [[0.0976, 11.5, 7.27, 0, 0.51, 5.2, 38, 5.23, 5, 309, 12.2, 370.5, 15.7]]
pred = modelo.predict(nuevo)
pred

c:\Users\HARVEY\anaconda3\envs\machine-learning\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([21.0369852])